name: Renovate Terraform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # manual trigger
  schedule:
    - cron: '0 3 * * 1'  # every Monday at 3am UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
