name: Trivy-to run mannually

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # To run workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  security-events: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Terraform Code Analysis using Trivy
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@master
      with:
          scan-type: 'config'

    - name: Scan Terraform for all type 
      uses: aquasecurity/trivy-action@master
      with: 
          scan-type: 'fs' 
          scan-ref: '.'  # Path to your Terraform files  
          format: 'sarif'
          scanners: 'vuln,secret,misconfig'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN' 
          exit-code: 0
