name: Trivy-to run mannually

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # To run workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  actions: read
  security-events: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Terraform Code Analysis using Trivy
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in IaC mode
      uses: aquasecurity/trivy-action@0.33.1
      with:
          scan-type: 'config' 
    - name: Run Trivy config scan and save output
      id: trivy
      run: |
          echo "Running Trivy scan..."
          trivy config > trivy_output.txt
          
          echo "trivy_output<<EOF" >> $GITHUB_OUTPUT
          cat trivy_output.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

    - name: Comment Trivy output on PR
      uses: peter-evans/create-or-update-comment@v4
      with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 🔍 Trivy IaC Scan Report
            <details>
            <summary>Click to expand</summary>

            ```
            ${{ steps.trivy.outputs.trivy_output }}
            ```

            </details>
